### ISSUE TITLE
Timer operator

### ISSUE THREAD

**Issue by teivah** [ReactiveX/RxGo#126]
`Timer` operator implementation

http://reactivex.io/documentation/operators/timer.html

**Comment by diogobeda** [comment]
Hey, I want to pick this one up if that's ok. Any objections? :)

**Comment by diogobeda** [comment]
Actually, it seems to be implemented already.

https://github.com/ReactiveX/RxGo/blob/v2/observablecreate.go#L414-L426

**Comment by teivah** [comment]
Oh, you're right @diogobeda thanks :) Let's close this one then.
What about this one if you want to pick up one? https://github.com/ReactiveX/RxGo/issues/143

**Comment by diogobeda** [comment]
Nice, that looks like a good one. Going to make it clear in the ticket that I'm picking that up. Thanks @teivah
