### ISSUE TITLE
TestSubscribeToManyObservers occasionally fails

### ISSUE THREAD

**Issue by jochasinga** [ReactiveX/RxGo#13]
This test will fail once every few times [here](https://github.com/jochasinga/RxGo/blob/1138cc5e1ebfeb2cd0e699960fb4d441d05d19ef/connectable/connectable_test.go#L203).

**Comment by VPashkov** [comment]
Hi!

The reason why this test fails is that nums array is accessed from different threads.
I see at least two straightforward but cumbersome ways to fix this test.
First one is to use mutex to synchronize access to nums array:
```go
mutex.Lock()
nums = append(nums, item.(int))
mutex.Unlock()
```
Second one is to use separate arrays for each Observer:
```go
nums1 = append(nums1, item.(int))
```
and then combine them into one array:
```go
var nums = append(append(nums1, nums2...), nums3...)
```
I checked. They both seems to work.
Which on do you think is better? Or maybe you see better options?

**Comment by jochasinga** [comment]
@VPashkov I think using `mutex` is a better approach. Using separate slices works too but in this case using a single slice better displays the behavior of several `Observer`s asynchronously putting value in. 

Why do you think it's cumbersome?

**Comment by VPashkov** [comment]
I thought `mutex.Lock()/mutex.Unlock()` calls will make a noise in code.
But now I see that it makes it more explicit.

**Comment by jochasinga** [comment]
@VPashkov yes it does. But using it sparingly is okay. I'm a fan of using what ever is available.

**Comment by VPashkov** [comment]
@jochasinga, sure. Done.
Sorry about that.
