### ISSUE TITLE
Support `Take` and `TakeLast` filter.

### ISSUE THREAD

**Issue by pocket7878** [ReactiveX/RxGo#14]
Add `Take` and `TakeLast` filter.

```
func (o Observable) Take(n int) Observable
func (o Observable) TakeLast(n int) Observable
```

http://reactivex.io/documentation/operators/take.html
http://reactivex.io/documentation/operators/takelast.html

**Comment by pocket7878** [comment]
@jochasinga 
Is it better to discuss before each PR or, open issue and send PR can be parallel?

**Comment by jochasinga** [comment]
@pocket7878 it can be parallel. Just that if we decide not to implement the feature it will save you the effort by not submitting the PR first. However, if you already planned to implement on your own fork then there's no reason why you shouldn't pay it backward :1st_place_medal: 

@pocket7878 great work anyway. I'll check the links out.
