### ISSUE TITLE
Implement Subject and its variants

### ISSUE THREAD

**Issue by makannan** [ReactiveX/RxGo#156]
Like RxJS & RxPy, we need a few implementations of Subject. Like `ReplaySubject`,  `BehaviorSubject` etc.

**Comment by teivah** [comment]
@makannan I'm fine with the idea, but could you please just add your comment in https://github.com/ReactiveX/RxGo/issues/54
There's already an issue for that otherwise we'll have duplicates.
Thanks ;)
