### ISSUE TITLE
Add Skip & SkipLast filters.

### ISSUE THREAD

**Issue by pocket7878** [ReactiveX/RxGo#17]
Add filters:

```
func (o Observable) Skip(nth uint) Observable
func (o Observable) SkipLast(nth uint) Observable
```

**Comment by pocket7878** [comment]
I'd sent PR, but I can't run `go test` locally since ownership was changed and I got `cannot find package` errors.

**Comment by jochasinga** [comment]
@pocket7878 can you open a separate issue on this? I'm trying to get @mattpodwysocki to work on the logistics since this change effected the Travis CI as well.
