### ISSUE TITLE
Close channel on unsubscribe or error from handler

### ISSUE THREAD

**Issue by dennypenta** [ReactiveX/RxGo#172]
observable/observable.go:452 will close the channel only when it finishes.
So if an error has occurred, the channel won't be closed.
It leads to memory and goroutine leak.
Can you show me the latest branch, I'll push the PR.

**Comment by dennypenta** [comment]
Created the PR.
https://github.com/ReactiveX/RxGo/pull/173

**Comment by teivah** [comment]
As mentioned in https://github.com/ReactiveX/RxGo/pull/173#issuecomment-500043182, please do not hesitate to reopen your PR if your tests are ok.
