### ISSUE TITLE
Catch operator

### ISSUE THREAD

**Issue by dennypenta** [ReactiveX/RxGo#174]
http://reactivex.io/documentation/operators/catch.html

**Comment by teivah** [comment]
Following operators implemented in the `v2` branch:
* `OnErrorResumeNext`
* `OnErrorReturn`
* `OnErrorReturnItem`

https://github.com/ReactiveX/RxGo/blob/6c1de57ec0e14f0cbccc951ed5a6b200dd211ef2/observable.go#L56-L58
