### ISSUE TITLE
Blocking connect operator discrepancy

### ISSUE THREAD

**Issue by dalianzhu** [ReactiveX/RxGo#176]
As we know, method `connectable.From` accepts an iter object. But if this iter object is channel, nothing will happen **until this chan is closed**. 
As shown in the code below：
```go
ch:=make(chan interface{}, 10)
//var ch = []interface{}{1,2,3,4}  is work
go func() {
    for{
        ch<-time.Now().Unix()
        time.Sleep(1*time.Second)
    }
}()

iter, _ := iterable.New(ch)

co := connectable.From(iter)

co = co.Do(func(item interface{}) {
    // will never printed
    fmt.Println("svc1", item)
})

<-co.Connect()
```
I just implemented it in my fork (even though it passed the test cases, but with many other flaws).
Or can we find out a better solution?
[https://github.com/dalianzhu/RxGo/blob/master/connectable/connectable.go](https://github.com/dalianzhu/RxGo/blob/master/connectable/connectable.go)

**Comment by teivah** [comment]
Hi @dalianzhu. Thank you for your contribution but honnestly I don't really understand the purpose of this issue. In my opinion, a PR should be juste a micro-service, meaning with a high-cohesion :)

Maybe, we can keep it dissociated from #44. This would really help me to understand what problem did you face and what solution did you propose.

**Comment by dalianzhu** [comment]
sorry to confuse you. @teivah. I modified the issue again. The issue is now method `connectable.From` accepts iter object, but if this iter obj is channel, it will block the process until this chan is closed. Is it necesary to find a solution?

**Comment by teivah** [comment]
No problem @dalianzhu. If I understand correctly your point, the issue you raised is not linked to the `From` operator but to the `Connect` one. 

For example the following example does not lead to any problem:
```go
ch := make(chan interface{})
c := From(newIteratorFromChannel(ch))

c.Subscribe(handlers.NextFunc(func(i interface{}) {
	fmt.Printf("%v\n", "foo")
}))

ch <- 1

fmt.Printf("%v\n", "bar")
```

Just for information, the API for connectable observable did change in the ongoing v2 branch to be closer to the other implementations.

That being said, I do believe you raised a good point. For example in Java:

```java
Observable<Long> observable = Observable.timer(2, TimeUnit.SECONDS);
ConnectableObservable<Long> publish = observable.publish();
publish.subscribe(l -> System.out.println("foo"));
publish.connect();
System.out.println("bar");
```

This will display `bar` then `foo` 2 seconds later which means the `connect` operator is not blocking. Whereas in RxGo (example taken from the v2 API):

```go
ch := make(chan interface{})
c := From(newIteratorFromChannel(ch)).Publish() // v2 change to create a connectable observable
got1 := make([]interface{}, 0)

c.Subscribe(handlers.NextFunc(func(i interface{}) {
	got1 = append(got1, i)
}))

c.Connect() // Blocking call

ch <- 1 // Never called
```

The last instruction is never called as `Connect()` does block until the internal iterator (in this case a channel) completes. This is definitely a discrepancy.

If you'd like to work on this (that would be more than welcome :), please do it from the v2 branch to change the behavior of the connect operator.

**Comment by teivah** [comment]
I made an implementation based on the v2 philosophy. There's a dedicated test for that: https://github.com/ReactiveX/RxGo/blob/6c1de57ec0e14f0cbccc951ed5a6b200dd211ef2/connectableobservable_test.go#L36

**Comment by teivah** [comment]
Btw, @dalianzhu if you want to participate anyhow, you would be more than welcome ;)

**Comment by dalianzhu** [comment]
@teivah thanks, this is a great work. I will use rxgo in my project and hope to make improvements in the future :)

**Comment by teivah** [comment]
@dalianzhu Using the v2 right? ;)

**Comment by dalianzhu** [comment]
@teivah yes, I only recently discovered the V2 version and will use it.

**Comment by teivah** [comment]
@dalianzhu To be transparent (and I think you already saw it), the v2 has not been released yet and is still under construction. I would not advise you to use it if you have tough time constraints for example. Yet, if you can, I would be very happy to support you as best as I can. Working directly with an end user is a great thing to construct a product ;)

**Comment by dalianzhu** [comment]
@teivah thanks a lot. Rxgo is an amazing project, it makes programming more interesting and easy. Now I use it in some micro-service, the code is not complex and it’s working well right now. I hope to help this project become better.
