### ISSUE TITLE
Complete the migration of the tests to ginkgo and gomega

### ISSUE THREAD

**Issue by teivah** [ReactiveX/RxGo#178]
In the v2 we started to migrate the tests to ginkgo and gomega. We have to complete the migration before releasing the v2.

**Comment by RahulZoldyck** [comment]
@teivah I can pick this up.

**Comment by teivah** [comment]
@RahulZoldyck Please do. Just make sure to start from the v2 branch. Cheers.

**Comment by teivah** [comment]
Abandoned: https://github.com/ReactiveX/RxGo/pull/205
