### ISSUE TITLE
Update travis.yml to manage dependencies using Go modules

### ISSUE THREAD

**Issue by teivah** [ReactiveX/RxGo#183]
We need to update `.travis.yml` file to use dependencies using Go modules instead of `go get` just like today.

**Comment by teivah** [comment]
@Sheshagiri That would be great thanks. Please note that there was a PR created by @exfly for that: https://github.com/ReactiveX/RxGo/pull/187
It has been closed (I don't know why) but maybe that could help you?
Also, this is a v2 feature so please start from the v2 branch.

**Comment by exfly** [comment]
@teivah I change the mod only, but ci failed.I need some help.

**Comment by Sheshagiri** [comment]
@exfly I see that travis passed on https://github.com/ReactiveX/RxGo/pull/187 let me know if I can be of any help :)

**Comment by teivah** [comment]
Implemented in v2.
