### ISSUE TITLE
Support for Repeat (Creating Operator)

### ISSUE THREAD

**Issue by ArekCzarnik** [ReactiveX/RxGo#19]
Have any one interest of Repeat Creating Operator? I would try to implement it.

---
http://reactivex.io/documentation/operators/repeat.html

Repeat
create an Observable that emits a particular item multiple times.
![Image of repeat](http://reactivex.io/documentation/operators/images/repeat.c.png)
The Repeat operator emits an item repeatedly. Some implementations of this operator allow you to repeat a sequence of items, and some permit you to limit the number of repetitions.

# code proposal (observable.go):

func Repeat() Observable 
func Repeat(ntimes int) Observable

**Comment by jochasinga** [comment]
@ArekCzarnik we can have an optional argument by mean of variadic function. That way if no `ntimes` is given it can default to repeating infinitely similar to [interval](http://reactivex.io/documentation/operators/interval.html).

**Comment by jochasinga** [comment]
By the way, @ArekCzarnik do you have problem running test locally? Since the ownership changed I was told this might be an issue.

**Comment by ArekCzarnik** [comment]
@jochasinga i have some issues with the tests, the imports are not correct:

github.com/jochasinga/rxgo - > should be more this -> github.com/reactivex/rxgo

after that i have running tests:

```
go test ./...                                                                                                                                                                                                                       08:50:53 
?       github.com/reactivex/rxgo       [no test files]
ok      github.com/reactivex/rxgo/connectable   0.616s
ok      github.com/reactivex/rxgo/errors        0.014s
?       github.com/reactivex/rxgo/examples/reactive_sum [no test files]
?       github.com/reactivex/rxgo/examples/scroll       [no test files]
?       github.com/reactivex/rxgo/fx    [no test files]
ok      github.com/reactivex/rxgo/handlers      0.012s
ok      github.com/reactivex/rxgo/iterable      0.015s
ok      github.com/reactivex/rxgo/observable    0.180s
ok      github.com/reactivex/rxgo/observer      0.013s
ok      github.com/reactivex/rxgo/subscription  0.025s
```

**Comment by ArekCzarnik** [comment]
> "we can have an optional argument by mean of variadic function. That way if no ntimes is given it can default to repeating infinitely similar to interval." 

@jochasinga sounds good,  i will try to implement it.
