### ISSUE TITLE
causalityDuration Hides code execution in `duration` method

### ISSUE THREAD

**Issue by v-zubko** [ReactiveX/RxGo#233]
https://github.com/ReactiveX/RxGo/blob/e94d354069f3579c0a0fcabe00738859dc5c0d94/duration.go#L84

It is not expected that `duration` method will actually do such sophisticated thing. I expect it to return duration value only.

**Comment by teivah** [comment]
I disagree, **it is** expected. Actually, that's the purpose of it. Let's see why with a concrete example.

There's this `BufferWithTime` operator that batches the items at a given frequency. How would we implement unit tests for that? Most likely using a couple of `time.Sleep()`, right?

Now, let's see how the nominal test is implemented:

```go
func Test_Observable_BufferWithTime(t *testing.T) {
	ctx, obs, d := timeCausality(1, 2, 3, tick, tick, 4, tick, 5, 6, 7, tick)
	obs = obs.BufferWithTime(d, WithContext(ctx))
	Assert(context.Background(), t, obs, HasItems(
		[]interface{}{1, 2, 3},
		[]interface{}{4},
		[]interface{}{5, 6, 7},
	))
}
```

Using `timeCausality()` that returns an Observable, we can configure whenever the timer is going to be triggered. This creates a **deterministic unit test** without any single `time.Sleep()`.

If you need a simple mock, you can use `mockDuration`.

**Comment by v-zubko** [comment]
I understand why it is there and how it works. My point is that it is not obvious and may confuse others. 
As to example with test it could be like this:
```
buf := Interval(WithDuration(time.Second), WithContext(ctx)).BufferWithTime(3 * time.Second, WithContext(ctx)).Observe()
assert.Len(t, buf, 3)
```

**Comment by v-zubko** [comment]
Another thing is that having pauses while sending data will hide things like this https://github.com/ReactiveX/RxGo/issues/234

**Comment by teivah** [comment]
Let's keep only https://github.com/ReactiveX/RxGo/issues/234
