### ISSUE TITLE
Timer will never trigger when you have data coming on a channel 

### ISSUE THREAD

**Issue by v-zubko** [ReactiveX/RxGo#234]
https://github.com/ReactiveX/RxGo/blob/e94d354069f3579c0a0fcabe00738859dc5c0d94/observable_operator.go#L477

Incoming data will continue to buffer and buffer will not be send down to pipeline because timer will never trigger.
Previous implementation of this function didn't have such problem.

**Comment by teivah** [comment]
Fixed in https://github.com/ReactiveX/RxGo/pull/236
