### ISSUE TITLE
Hot/Cold observable examples mixed up?

### ISSUE THREAD

**Issue by orsenkucher** [ReactiveX/RxGo#238]
I have a feeling `Hot`/`Cold` observable examples are mixed up. 
And from my experience with Rx I say they really are.
Check this [paragraph](https://github.com/ReactiveX/RxGo#hot-vs-cold-observables) in README, please.

**Comment by jochasinga** [comment]
@orsenkucher looks like you're right. Would you like to create a PR?

**Comment by orsenkucher** [comment]
Sure, wait for it

**Comment by teivah** [comment]
Merged, thanks @orsenkucher
