### ISSUE TITLE
Support for Scheduler in Repeat Operator

### ISSUE THREAD

**Issue by ArekCzarnik** [ReactiveX/RxGo#24]
Have any intresst on scheduler implementation in Repeat Operator ? 
One usefull usescase can be to call every 5 minute a rest api.
I would try to implement it.

# code proposal (observable.go):
func Repeat(item interface{},cronspec string) Observable 

# useage (pseudocode)
```go
schedulerstream := Repeat("http://www.example.com", "@every 5m") 
reponsestream := schedulerstream.Map('...make httpcall...')
```
and 
```go
schedulerstream := Repeat("http://www.example.com", "*/5 * * * *")
reponsestream := schedulerstream.Map('...make httpcall...')
```

**Comment by jochasinga** [comment]
Hi @ArekCzarnik,

I am not sure how useful this is, or maybe because I'm still learning. Do
you have experience with any other RX in other languages with this feature?

**Comment by ArekCzarnik** [comment]
Hi jochasinga,

yes , currently i use JavaRX in some of my work projects.And i use this feature to build a "simple background polling".

for example (pseudocode):
```java
Observable.interval(5, TimeUnit.MINUTES)
          .map(tick -> httpService.getResponse())
          .doOnError(err -> log.error("Error http response", err))
          .retry()
          .subscribe(response -> log.info(response.getBody().toString())
```
maybe the interval operation is a better place for "cron/tick/scheduler" operations...

**Comment by jochasinga** [comment]
@ArekCzarnik it does look odd and not very idiomatic providing `cronspec` as a string. It should be a [functional option](https://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis) or struct.

```go

// Example of using a struct
type Cron struct {
        spec string
}

myspec := Cron{"@every 5m"}
scheduler := Repeat("http://www.example.com", myspec)

```

Somehow I think functional options are cleaner.

**Comment by avelino** [comment]
implemented on RxGo 2 (in development) https://github.com/ReactiveX/RxGo/pull/115
