### ISSUE TITLE
How to merge, order and distinct 2 observables

### ISSUE THREAD

**Issue by segator** [ReactiveX/RxGo#247]
I have 2 observables
first one read from repository and takes arround 1s-5minutes(are fully ordered)
I have another one with realtime data, can be un-ordered or even duplicated(those can already be in first observable).
I succesfully merge both, but I don't know how to order them by incremental sequence,
every object have a sequenceID unique and must be incremental,
example

Ob1 |1-2-3-4-5-6-7-8 | <-- channel is closed here
Ob2 ----------9-------10----6-7------12-8---10-----11

**expected result**
|1-2-3-4-5-6-7-8-9---10------------------------------11-12-----

**Comment by teivah** [comment]
In your example, you seem to have duplicates. I'm not sure what do you expect then.
If you check this [test](https://github.com/ReactiveX/RxGo/blob/7a403b9a292df583de81de3e471553db61112cd2/observable_operator_test.go#L1297), the behaviour is currently limited in the face of duplicates.

Maybe we could have two options, one to discard them or one to reset the sequenceID basically.
What do you think?

**Comment by segator** [comment]
Hey Thanks for answer!
Yes there are duplicates and I confirm content is exactly same, is not a big deal.
The important is that the output is ordered and without duplications so we can discard randomly one or other duplicated of both queues.

So serialize does the "distinct", but I think the hard point here is how to ensure that if a queue is missing the next number should get it from the other one as the sequence are in order and is secuential

**Comment by teivah** [comment]
If the merged observable:
* Does not contain duplicate
* Contain the sequence ID from the initial value to whatever value regardless the order
Then it's going to work
For example:
* Obs1: 1-3-4-8
* Obs2: 2-6-5-7-9
After merging and serializing, it'll produce 1-2-3-4-5-6-7-8-9

**Comment by segator** [comment]
I could have a try :)

So I need to use concat and then serialize right? 
Just starting with golang and all this reactive programming stuff with your library, sorry for the dummy questions,
I apreciate your help!

**Comment by teivah** [comment]
Closing this because of the lack of activity. In case, please reopen a ticket.
