### ISSUE TITLE
GroupBy with dynamic lenght 

### ISSUE THREAD

**Issue by tfirsiuk** [ReactiveX/RxGo#253]
Current GroupBy transforming observable gets predefined lenght. When I want to split data by ID which is uint16 I have to set length to ^uint16(0). This will create loads of observables that wil never be used. In some cases I will have only 10 different IDs but at the point of creating GroupBy observable I'm not able to predict the number of differend IDs. 
Is it possible to solve my issue with current rxgo observables set or add some kind of dynamic GroupBy feature? What could be the down side of making GroupBy generating new observables for keys in runtime?   
Thanks in advance for response.

**Comment by teivah** [comment]
Hi @tfirsiuk,
I'm sorry I didn't get your example.

**Comment by tfirsiuk** [comment]
Hi @teivah, 
Sure, I'll try to put this in a different way. I have, let's say 3 objects which constantly generate frames into one observable. I want to dispatch these frames from one observable into separate 3 observables, one observable for each object. Each object has its own ID (eg. obj1:20, obj2: 205, obj3: 1055). To achieve this I use GroupBy which is grouping by ID all frames from the objects so that I end up with 3 observables, each of those with frames from only one object ID. This works for me. 
The (minor) issue I see here is that GroupBy needs to get length, which in above case is at least 1055 because I'm grouping by ID. Also in this case GroupBy will create exactly 1055 new observables basing on given length, only 3 of them will be used. 
I think that it will be good to make GroupBy working that way so it's creating a new observable only if at least one object's frame  appears. If eg. ID=5 won't send any frame than GroupBy does not create any observable for ID==5.
Hope this makes sense.

**Comment by teivah** [comment]
@tfirsiuk I got what you meant, thanks. Please check at https://github.com/ReactiveX/RxGo/pull/255 or directly `go get -u github.com/reactivex/rxgo/v2@groupbydynamic`. 

I've added a `GroupByDynamic`. It will produce an observable producing `GroupedObservable`s (which is a structure on top of an observable). I needed this as we may be interested in knowing what's the key of the operator.

Would that fit your need?

**Comment by tfirsiuk** [comment]
Hi @teivah, just tested this. It is exactly what I wanted and it works like a charm. 
Thanks

**Comment by teivah** [comment]
@tfirsiuk Cool. I'll finish the work of merging it into master this week with proper documentation. I'll let you know.

**Comment by teivah** [comment]
@tfirsiuk I've just merged the change into master and released [v2.2.0](https://github.com/ReactiveX/RxGo/releases/tag/v2.2.0). Let's close this ticket.
Thanks for your suggestion, feel free to open a new one if you spot anything else that could be improved 😉
