### ISSUE TITLE
Add CombineLatest operator.

### ISSUE THREAD

**Issue by pocket7878** [ReactiveX/RxGo#26]
Add 
```
func CombineLatest(o ...Observable,map func (is []interface{}) interface{}) Observable
```

**Comment by jochasinga** [comment]
@pocket7878 Why `CombineLatest` and not `Combine`?

**Comment by psh** [comment]
I believe the strongest reason to go with ```CombineLatest``` over ```Combine``` would be that it follows the documentation on Rx operators - http://reactivex.io/documentation/operators.html

**Comment by jochasinga** [comment]
@psh thanks for the heads up. @pocket7878 would you like to work on this one?
