### ISSUE TITLE
"Take" operator does not end the stream?

### ISSUE THREAD

**Issue by sky91** [ReactiveX/RxGo#262]
Version: v2.3.0
Type: question
Description:
I find that **takeWhileOperator** [invoke operatorOptions.stop()](https://github.com/ReactiveX/RxGo/blob/3d2c2bf0c8927f0e5736851aac501de880bb1ada/observable_operator.go#L2495) to end the stream, and so does [**takeUntilOperator**](https://github.com/ReactiveX/RxGo/blob/3d2c2bf0c8927f0e5736851aac501de880bb1ada/observable_operator.go#L2463). But **takeOperator** [does not](https://github.com/ReactiveX/RxGo/blob/3d2c2bf0c8927f0e5736851aac501de880bb1ada/observable_operator.go#L2381).
A stream like `rxgo.Interval(rxgo.WithDuration(2 * time.Second)).Take(3)` never completes.
Meanwhile, the figure in the [doc/take.md](https://raw.githubusercontent.com/ReactiveX/RxGo/v2.3.0/doc/take.md) shows that **Take** will end immediately after an enough count.
Is current behavior of **takeOperator** correct?

**Comment by teivah** [comment]
Thanks @sky91, it was definitely an incorrect behaviour 👍
