### ISSUE TITLE
GroupByDynamic with key of type other than int

### ISSUE THREAD

**Issue by cc-stjm** [ReactiveX/RxGo#264]
It'd be helpful to be able to do GroupByDynamic with a key that isn't int... I'd suggest string, as this is probably the most versatile. 

If the key function returns a fmt.Stringer rather than a string, that might be nicer as in some cases 

From the look of https://github.com/ReactiveX/RxGo/pull/255/files there's no reason that the key can't be another type (other than you'll need to make a new func for each type...)

**Comment by teivah** [comment]
Hey @cc-stjm,
Are you proposing to change the signature of `GroupByDynamic` to `GroupByDynamic(distribution func(Item) string, opts ...Option) Observable`? If yes, I'm not sure to follow the added value.

**Comment by cc-stjm** [comment]
I'd suggest creating a new function, to avoid existing users having breaking changes, but otherwise, yes.

A concrete example - we need to do a group by of GUIDs, which are 128 bit and so will not fit into an int - so any hashing function to convert them to ints could lead to clashes. Converting them to a string representation for the keys guarantees the uniqueness remains.

More generally, if the group by is using strings then (pretty much) any data type can be converted - including dates (choose a standard string representation), complex objects (serialize to json) etc. - there's a lot more flexibility than you get with an int.

**Comment by teivah** [comment]
Thanks for the explanation @cc-stjm, it makes a lot of sense. Are you okay with https://github.com/ReactiveX/RxGo/pull/267?
If yes I can merge it and release a new version.

**Comment by cc-stjm** [comment]
Thanks, yes that looks great!

**Comment by teivah** [comment]
Great, I have just released a v2.4.0.
Thanks for your contribution @cc-stjm
