### ISSUE TITLE
Proposal - change Observer to interface

### ISSUE THREAD

**Issue by venth** [ReactiveX/RxGo#28]
Hi,

I've tried to create TestObserver to simplify testing process. 
`
type TestObserver{
  observer.Observer
}
`
Unfortunately there was no way to subscribe custom observer (TestObserver in my case). Working code looked like that:
`
sequence.subscribe(testObserver.Observer)
`
I scrutinized source code and saw that Observer is a struct. If observer would be interface then there will be no issue.  I made a try of Observer interface introduction.

I replaced Observer with wrappingObserver (private to keep one entry point - New function in observer package). Then introduced Observer interface. There was no need to keep rx.EventHandler - handlers conversion in kept in handlers package.

If you consider the proposal is valid, please take a look at: https://github.com/venth/RxGo/tree/introduction-of-observer-interface

I stored there afore mentioned changes.

**Comment by jochasinga** [comment]
Thanks @venth 
I haven't taken a jab at your code much yet, but my goal is to eventually make `Observer` and `Observable` interfaces. Here's a question. Can a stream call `.Subscribe` method with a handler func as a param with this change?

```go

stream.Subscribe(handlers.NextFunc(someFunc))

```

The goal is `Subscribe` should accept an interface (right now it's `EventHandler`) so it's flexible enough to accept an "Observer" (loosely a collection of `OnNext`, `OnError`, and `OnDone`) or just either of the handlers.

**Comment by venth** [comment]
Yes, it is. Perhaps I could write few test to prove my words. Partially it's proven by tests in observer_test. Shortly: `Subscribe` accepts:
* object implementing Observer interface
* func(item{})
* handlers.NextFunc(someFunc)
* func(error)
* handlers.ErrFunc(someFunc)
* func()
* handlers.DoneFunc(someFunc)
For instance:
* sequence.Subscribe(func(item interface{} {})
* sequence.Subscribe(func(err error) {})
* sequence.Subscribe(func() {})
* sequence.Subscribe()
* sequence.Subscribe(func(item interface{} {}, func(err error) {}, func() {})
* sequence.Subscribe(handlers.NextFunc(func(item interface{} {}), func(err error) {}, func() {})
* sequence.Subscribe(func(item interface{} {}, handlers.ErrFunc(func(err error) {}), func() {})
* sequence.Subscribe(anObserver)
* and so on ;)

**Comment by jochasinga** [comment]
Since this looks like a breaking change, can you do a PR to the `dev`branch?

**Comment by venth** [comment]
I've created pull request to dev branch

**Comment by jochasinga** [comment]
Since `Subscribe` accepts both:
- `handlers.NextFunc` and `func(interface{})`
- `handlers.ErrFunc` and `func(error)`
- `handlers.DoneFunc` and `func()`

It is hard to justify keeping these types in `handlers` at all. While it seems like a better idea, when I was designing it was my intention to follow the pattern used in Go, most apparent in `net/http` when you have a `HandleFunc` to explicitly "convert" a function with the signature `func(http.ResponseWriter, *http.Request)` to a `Handler`. 

The point is you are not allowed to use both `func(http.ResponseWriter, *http.Request)` and `http.Handler`.

What is your take on this?

**Comment by venth** [comment]
I like concise code that's why I thought it would be more convenient to write:
`anObservable.subscribe(func(item) { ... })` rather than
`anObservable.subscribe(handlers.NextFunc(func(item) { ... }))`

For me the second example has a buzz: `handlers.NextFunc(...)` which obscures the intention.
