### ISSUE TITLE
Range(start, count) behavior not corresponding with docs

### ISSUE THREAD

**Issue by ospiper** [ReactiveX/RxGo#282]
**Describe the bug**
According to the image of [docs here](https://github.com/ReactiveX/RxGo/blob/master/doc/range.md), the second argument indicates *length* of the iterator (i.e. `start ... (start+count-1)`), but in [code here](https://github.com/ReactiveX/RxGo/blob/master/iterable_range.go#L22) the actual range gets to be `start ... (start+count)` which is not expected from the documentations.

**To Reproduce**
```go
for i := range rxgo.Range(0, 3).Observe() {
	fmt.Println(i.V.(int))
}
```
outputs: 
```
0
1
2
3
```

**Expected behavior**
```
0
1
2
```

**Comment by maguro** [comment]
PR filed https://github.com/ReactiveX/RxGo/pull/288.
