### ISSUE TITLE
Is it ready to be used in a production environment?

### ISSUE THREAD

**Issue by ctlove0523** [ReactiveX/RxGo#286]

**Comment by maguro** [comment]
imo, it is not.  There are a few critical bugs, one has been fixed by a PR I filed a few days ago.

Also, a broken CI pipeline that hasn't been fixed in months is a serious red flag.

**Comment by ctlove0523** [comment]
> imo, it is not. There are a few critical bugs, one has been fixed by a PR I filed a few days ago.
> 
> Also, a broken CI pipeline that hasn't been fixed in months is a serious red flag.

Get it,thanks
