### ISSUE TITLE
Example for ZipFromIterable gives output different from doc

### ISSUE THREAD

**Issue by ashwineaso** [ReactiveX/RxGo#287]
**Description**
According to the documentation provided for the ZipFromIterable Operator [here](https://github.com/ReactiveX/RxGo/blob/master/doc/zipfromiterable.md) the output on running the example code is 

```
11
12
13
```

But the actual output seems to be
```
11
22
33
```

**Additional context**
The actual output on running the example code seems to differ from the output provided in the documentation. Documentation needs to be updated if that is found to be true.

**Comment by maguro** [comment]
The docs seem to be wrong.  Would you like to submit a PR to update?
