### ISSUE TITLE
Confusion in import paths & docs on pkgsite

### ISSUE THREAD

**Issue by pashaosipyants** [ReactiveX/RxGo#299]
**Describe the bug**
There is a confusion between paths: 
- github.com/ReactiveX/RxGo _(original)_
- github.com/reactivex/rxgo _(module)_

As the result there are different doc pages on the pkg site.
https://pkg.go.dev/github.com/reactivex/rxgo
https://pkg.go.dev/github.com/ReactiveX/RxGo - does not contain info about **v2**
This is actually very confusing. I've spent some time learning RxGo v1, because the link above said it's the latest version... :(

Look at [this](https://github.com/golang/go/issues/45140) issue for additional information.
Particularly, golang contributors suggested:
> I would recommend asking the authors to request for github.com/ReactiveX/RxG to be excluded from pkg.go.dev, per https://go.dev/about#removing-a-package.

**Comment by teivah** [comment]
Hi @pashaosipyants,
Thanks for having filled a ticket. I don't think the package should be removed as people may still want to use it and there are still multiple consumers. Also, naming the module with the major version, starting from v2 was done purposely.
What I've just done though, is a small update to make things clear in the doc that the v1 is deprecated. It will become visible in pkg.go.dev soon, I guess.
