### ISSUE TITLE
Merge into ReactiveX project?

### ISSUE THREAD

**Issue by JensRantil** [ReactiveX/RxGo#3]
The ReactiveX has an RxGo project which [doesn't have any code](https://github.com/ReactiveX/RxGo/issues/2). How about contributing this code there?

**Comment by jochasinga** [comment]
@JensRantil yes I'm aware of that. I can try sending a PR to the project once this becomes stable enough.

**Comment by mattpodwysocki** [comment]
@jochasinga please do ping me when you are ready and I'll help move it over

**Comment by jochasinga** [comment]
@mattpodwysocki what's on your mind? Ownership transfer or merge?

**Comment by mattpodwysocki** [comment]
@jochasinga I'd love for you to continue working on it and be the admin with it being under the ReactiveX org.  Therefore makes it easier for folks to find and contribute to it.  I'll get rid of the stub we have there and you can move it over if you wish.  Up to you!

**Comment by jochasinga** [comment]
@mattpodwysocki I agree! If there's any particular steps/guidelines for reactiveX org, feel free to let me know.

**Comment by mattpodwysocki** [comment]
@jochasinga can you make me an admin of the group so I can move it over?  Also, I made you an admin of the RxGo group which will be effective once we move the repo

**Comment by jochasinga** [comment]
@mattpodwysocki you mean transfer ownership of the repo to you.

**Comment by mattpodwysocki** [comment]
@jochasinga just admin access should suffice instead of the push access so I can transfer it

**Comment by jochasinga** [comment]
@mattpodwysocki as far as I know there's no way to grant admin access to a collaborator for a user-account repository other than to transfer ownership (?) Or is there a way I can move this to the rxgo team. Please advice.

**Comment by mattpodwysocki** [comment]
@jochasinga ok, transfer it to me, then I'll move it over

**Comment by mattpodwysocki** [comment]
@jochasinga done!
