### ISSUE TITLE
Why was `vendor/` added?

### ISSUE THREAD

**Issue by maguro** [ReactiveX/RxGo#311]
Just curious.  What problems did adding it solve?

**Comment by teivah** [comment]
I'd say mainly:
* Perfectly reproducible builds over time (even if repos are deleted)
* No need to handle cache during CI

Other popular repos in Go do the same, for example [Kubernetes](https://github.com/kubernetes/kubernetes/tree/master/vendor).

**Comment by maguro** [comment]
So the concern is that a project might get deleted?

What problems w/ caching occur during CI?  Sounds interesting.

**Comment by teivah** [comment]
There's no strong requirement as the project was working already without vendoring but there are some benefits imo.

**Comment by maguro** [comment]
Agreed,  I was just wondering what problems w/ caching occur during CI.

**Comment by teivah** [comment]
Since I switched to GH actions, things were smoother than with Travis. So, no strong requirements but it's becoming more and more the norm. 
Let's close it then, if you're okay.
