### ISSUE TITLE
Broken external link on README for Yomo

### ISSUE THREAD

**Issue by darrensapalo** [ReactiveX/RxGo#331]
**Describe the bug**
Link to yomo.run/rx on readme is broken (https://yomo.run/rx)

**To Reproduce**
1. Read the readme

**Expected behavior**
The URL works

**Additional context**
Haven't lurked in yomo to find their section why they chose rx yet. Lining this up for something for me to do on a weekend.

**Comment by teivah** [comment]
Thanks @darrensapalo for reporting it.
