### ISSUE TITLE
How to dispose a subscription?

### ISSUE THREAD

**Issue by imkerberos** [ReactiveX/RxGo#34]
As the example code:
`
subscription := observable.Subscribe(observer)
`
The Subscribe function will return a disposable in other Rx implementations such as RxSwift, RxJS etc.
But in RxGo, I think that shouldn't return a subscription when call Subscribe.

In sources, I found that an observable is a chan. I think that it's an error prototype. Thinking that we want to implement the operators "Materialize/Dematerialize" or "Combine/Merge/Concat" or "Catch". The observable should process error event, next event and completed event.

code proposal:
`
dispose := observable.Create(func(o observer.Observer) disposable.Disposable{
    // create a network request
    // .............
   return disposable.Disposable(func(){
        // cancel network request.
   })
})
`

Sorry for my poor english.

**Comment by jochasinga** [comment]
Hi @imkerberos thanks for your proposal. I have not thought all the way to that yet, thought I have dabbled into subscription. Fact is I want this project to strike a good balance between Rx and the Go language, and not trying to implement everything from Rx.

I think the ideal goal is to make Observable and Observer interfaces and not bounded to a single implementation.

I'll look into it and thanks for your PR. Looks cool.

**Comment by teivah** [comment]
For information, I tried to handle such use-case. Yet, I'm not tied to a particular way to create the `Observable`.

For example:
```go
sub := From(iterator).Subscribe(handlers.NextFunc(func(i interface{}) {
	// Some handler
}))

// Do something
sub.Dispose()
```

This will close the given subscription and it works regardless the creation operator used.
