### ISSUE TITLE
An old, different implementation of Rx in Go you might be interested in

### ISSUE THREAD

**Issue by thenikso** [ReactiveX/RxGo#37]
Hello there!

I was dusting off some old projects and I stumbled upon this https://github.com/thenikso/gorx from 2014

To be honest I don't quite remember what I was doing there :sweat_smile: however I kind of remember I did some work to support go routines quite nicely.

I don't know maybe it is something you might want to take a look at, that's all.

Best (and feel free to close this)

**Comment by jochasinga** [comment]
@thenikso very kind of you. It would be awesome if you could help out here too.
