### ISSUE TITLE
Cold & Hot Observables

### ISSUE THREAD

**Issue by anyoptional** [ReactiveX/RxGo#388]
As doc says, hot vs cold Observables are not about how you consume items, it's about where data is produced.  But when I dive deep into the code , it seems fromChannel & fromEventSource operator produces items act as the same way（items are produces from an external chan）, how dould I understand this?

**Comment by hunshenshi** [comment]
fromChannel & fromEventSource are hot Observables. The diff is fromChannel create an Observable based on a **lazy** channel, fromEventSource create an Observable based on an **eager** channel.
