### ISSUE TITLE
How to use Observables for emitting events?

### ISSUE THREAD

**Issue by twatzl** [ReactiveX/RxGo#39]
Hello,

I have a question about the usage of rxgo.

When using rxjs I usually use Subjects and .asObservable to get a simple event pattern. However in rxgo there is no Subject (yet?) and from the tutorials I could not find any way to pass data at runtime.
In the tutorials all observers are generated from existing arrays or functions which provide data, however Usually I would do something like this:
```
type MyStruct struct {
    s subject.Subject
}

func NewMyStruct() MyStruct {
    m := MyStruct{}
    m.s = subject.New()
    return s
}

func (m *MyStruct) doSomeActionWithNewValue(value interface{}) {
    m.s.Next(value)
}

func(m *MyStruct) getObservable() observable.Observable {
    return m.s.AsObservable()
}

func main() {
    myStruct := NewMyStruct()
    myStruct.getObservable().Subscribe(func(value interface{}) {
        // do work here
    }
    myStruct.doSomeActionWithNewValue("hello world")
}
```

Is it just because subjects are not yet implemented or is it intended to do something like this in a totally different way in go?

I already tried using a channel as base for the observable and using closures to provide a provider function for the observable, but both resulted in go telling me, that my application deadlocked, when waiting for the subscriptions.

**Comment by raininfall** [comment]
Using iterable

```go
input := make(chan interface{})
iter, _ := iterable.New(input)
source := From(iter)
source.Subscribe(handlers.NextFunc(func(value interface{}) {
	// do work here
}))
input <- "hello world"
```

Or you can impl your own Iterator 
https://github.com/ReactiveX/RxGo/blob/master/iterator.go

**Comment by jochasinga** [comment]
`Subject` is simply an Observer and Observable, and I don't see a good use to implement this at this point. As per @raininfall you can implement an `Iterator` for your case or wrap a `<-chan interface{}` with `Observable`:

```go

input := make(chan interface{})
go func() {
        input <- "hello world"
        close(input)
}()

<-Observable(input).Subscribe(myHandler)

```

**Comment by jochasinga** [comment]
Closing and merging with issue #54
