### ISSUE TITLE
A question about signal processing in the Connectable.Connect method.

### ISSUE THREAD

**Issue by LLLeon** [ReactiveX/RxGo#44]
Hello there!

When I read the source code, I am confused about the way the signal is handled:

```go
go func(ob observer.Observer) {
			<-fin
			if sub.Error == nil {
				ob.OnDone()
				sub.Unsubscribe()
			}

			go func() {
				temp <- sub // Because no one reads sub, so it will be blocked here
				fmt.Println("test") // The code can not be executed here.
				done <- temp // So temp will not be sent to done, it is impossible for others to read the temp from done.
			}()
			wg.Done()
		}(ob)
```

But when I run the test program, it passes the test.

```go
func TestDoOperator(t *testing.T) {
	co := Just(1, 2, 3)
	num := 0

	nextf := func(item interface{}) {
		num += item.(int)
	}

	co = co.Do(nextf)
	sub := co.Connect()
	v := <-sub
	fmt.Println("v --->", v)

	assert.Equal(t, 6, num)
}
```

It prints out the result is:

```shell
v ---> <nil>
```

Do not know if I have a clear expression, why is this handled? Hope to get help, thank you for your answer.

**Comment by jochasinga** [comment]
Can you paste the permalink to the line in the source code you are referring to? Also, can you try the following:

```go

sub := co.Connect()
if v, ok := <-sub; ok {
        fmt.Println("v --->", v)
}
assert.Equal(t, 6, num)

```

**Comment by LLLeon** [comment]
This is the permalink to the first piece of code: https://github.com/ReactiveX/RxGo/blob/23f38f99d1c3fadfb560f5f7ac2fce17b9ebc03d/connectable/connectable.go#L190
This is the permalink to the second piece of code: https://github.com/ReactiveX/RxGo/blob/23f38f99d1c3fadfb560f5f7ac2fce17b9ebc03d/connectable/connectable_test.go#L53

And I had tried to do it:
```go
func TestDoOperator(t *testing.T) {
	co := Just(1, 2, 3)
	num := 0

	nextf := func(item interface{}) {
		num += item.(int)
	}

	co = co.Do(nextf)
	sub := co.Connect()
	if v, ok := <-sub; ok {
		fmt.Println("v --->", v)
	}
	fmt.Println("no vvvvvvvvv")
	<-sub

	assert.Equal(t, 6, num)
}
```
The test results are like this:
```shell
❯ go test
no vvvvvvvvv
PASS
```
I'm still confused about it:
```go
go func() {
	temp <- sub // Because no one reads sub, so it will be blocked here
	fmt.Println("test") // The code can not be executed here.
	done <- temp // So temp will not be sent to done, it is impossible for others to read the temp from done.
}()
```
I guess `done <- temp` can not be executed. 
Thanks!

**Comment by jochasinga** [comment]
This code:

```go

if v, ok := <-sub; ok {
        fmt.Println("v --->", v)
}

```

does not block/wait. It reads from `sub` and prints if it's immediately available, which it never is at that point.

In order to make sure the goroutine in the pipeline finishes before doing anything else, you must block-wait for it.

```go

// ...
sc := co.Connect()
for sub := range <-sc {
        if s, ok := <-sub; ok {
                fmt.Printf("%v is done", s)
        }
}

Also note that `co.Connect()` returns a `<-chan (chan subscription.Subscription)`, because a connectable emits a resulting Subscription object for every goroutine it creates for each observer it subscribes to, hence the nested loops.




```

**Comment by LLLeon** [comment]
Sorry, I still don't understand. Maybe my question is not clear.

I try this code, but it doesn't work. 

```go
sc := co.Connect()
for sub := range <-sc {
        if s, ok := <-sub; ok {
                fmt.Printf("%v is done", s)
        }
}
```

This is the result:

```shell
./connectable_test.go:66:15: invalid operation: <-sub (receive from non-chan type subscription.Subscription)
FAIL    _/Users/LLLeon/Golang/RxGo/connectable [build failed]
```

I think it's because `sub` is `nill`. Just like the last test result.

```
v ---> <nil>
```

And what puzzles me is this piece of code:

https://github.com/ReactiveX/RxGo/blob/23f38f99d1c3fadfb560f5f7ac2fce17b9ebc03d/connectable/connectable.go#L197


```go
go func() {
	temp <- sub // There is no buffer in temp, so sub can only be put in when someone receives from temp, it'll blocked here.
	done <- temp // This line of code will not be executed.
}()
```

Is that correct? 
@jochasinga

**Comment by dalianzhu** [comment]
I have the same issue and i think you are right. 
```
go func() {
				temp <- sub
				fmt.Println("hahaha")
				done <- temp
			}()
```
hahaha can never be printed.

**Comment by teivah** [comment]
Hey! I'm cleaning the backlog by removing the issues without updates for more than a year. Meanwhile, please check at the v2 to see if the issue is still relevant.
