### ISSUE TITLE
Retry operators

### ISSUE THREAD

**Issue by pierrebeaucamp** [ReactiveX/RxGo#50]
As per contribution guidelines, I'm opening an issue for discussion regarding the implementation of Retry.

Per Documentation:

> The Retry operator responds to an onError notification from the source Observable by not passing that call through to its observers, but instead by resubscribing to the source Observable and giving it another opportunity to complete its sequence without error. Retry always passes onNext notifications through to its observers, even from sequences that terminate with an error, so this can cause duplicate emissions (as shown in the diagram above)

I have an implementation of `Retry` on my for, as linked below

reference: http://reactivex.io/documentation/operators/retry.html

**Comment by teivah** [comment]
Implemented in https://github.com/ReactiveX/RxGo/pull/215 as part of the v2
