### ISSUE TITLE
Implement Subject, or at least document a replacement prominently

### ISSUE THREAD

**Issue by sorsasampo** [ReactiveX/RxGo#54]
Coming from other ReactiveX language bindings, it's confusing not to find a direct Subject equivalent.

The only documentation is reading the source of `Observable` and realizing it's a wrapper for `<-chan interface{}` and figuring it out from there, or coming across [@jochasinga's comment](https://github.com/ReactiveX/RxGo/issues/39#issuecomment-327985004) on issue #39.

**Comment by jochasinga** [comment]
Care to discuss this? http://davesexton.com/blog/post/To-Use-Subject-Or-Not-To-Use-Subject.aspx

**Comment by teivah** [comment]
Hey! I'm cleaning the backlog by removing the issues without updates for more than a year. Meanwhile, please check at the v2 to see if the issue is still relevant.
