### ISSUE TITLE
Observable emits items only to first Observer reading from the wrapped channel

### ISSUE THREAD

**Issue by sorsasampo** [ReactiveX/RxGo#55]
Due to `Observable` being only [a simple `<-chan interface{}` wrapper](https://github.com/ReactiveX/RxGo/blob/23f38f99d1c3fadfb560f5f7ac2fce17b9ebc03d/observable/observable.go#L15-L16), items sent to the channel will only be received by one of the subscribed `Observer`s.

The expected behavior would be for every `Observer` to receive the same items sent to the underlying channel. This is how it works in other ReactiveX implementations.

**Comment by marcellanz** [comment]
@sorsasampo, under "Multiple Observers" in http://reactivex.io/documentation/contract.html it's stated that
> There is no general guarantee that two observers of the same Observable will see the same sequence of items.

in that sense that would hold the Observable Contract, wouldn't it?

**Comment by sorsasampo** [comment]
I disagree. The whole text is (emphasis mine):

> If a second observer subscribes to an Observable that is already emitting items to a first observer, it is up to the Observable **whether it will thenceforth emit the same items to each observer, or whether it will replay the complete sequence of items from the beginning to the second observer, or whether it will emit a wholly different sequence of items to the second observer**. There is no general guarantee that two observers of the same Observable will see the same sequence of items.

I think this refers to buffering Observables like ReplaySubject etc.

As far as I know, RxGo is the only ReactiveX implementation that emits items to a random Observer. That is broken no matter how I look at it.

**Comment by jochasinga** [comment]
@sorsasampo that's because Go pipelines are all about distributing items evently among Observers, not buffering the item sequence so all Observers observing the Observable get the same items. If you think about it, it's like copying a sequence `N` times to satisfy `N` Observers.

That being said, the goal is to promote `Observable` to an interface type and `<-chan interface{}` type can be one of the implementations, probably named `ObservableAsChannel` or something better.

**Comment by sorsasampo** [comment]
[Go pipelines](https://blog.golang.org/pipelines) may be. However, I believe a major point of ReactiveX is consistency between implementations, so I hope that will get improved.

**Comment by jochasinga** [comment]
I guess we have to weigh between consistency between reactiveX implementations and being idiomatic and (possibly) efficient in Go. This depends on a few things, but mostly a question of whether 

- [ ] People use reactiveX across multiple languages' implementation, and come to RxGo and got surprised by its difference OR
- [ ] People use vanilla Go and enter RxGo, in which case they will likely be more familiar with the way Go does things

To my understanding, most reactiveX implementations in different languages are different in some ways, and when there's a decision to either stick to hard reactiveX guideline OR the idiom of that particular language, the latter is more favorable.

For example just to make a case, here I use `OnDone` instead of `OnComplete` because Gophers are more familiar with the term "done".

Once an `Observable` becomes an interface, this implementation (`<-chan interface{}`) can be just one of many. You can imagine a ["ListAsObservable" synchronous implementation using a slice](https://github.com/jochasinga/rxgo-lite/blob/master/types/list.go), in which @sorsasampo 's proposed behavior can be better implemented.

**Comment by sorsasampo** [comment]
One of the major selling points of ReactiveX is "cross-platform":

> Available for idiomatic Java, Scala, C#, C++, Clojure, JavaScript, Python, Groovy, JRuby, and others

I have personally used RxClojure, RxJava, RxJS and RxScala. It's true there are slight differences between implementations for practical reasons, but in general as a ReactiveX user I expect consistency across language bindings. It's one of the most awesome things about ReactiveX! Learn it once and you can leverage that knowledge for other languages as well.

I'm not vouching for disregarding Go specifics. I think it would be best to maintain consistency to other ReactiveX implementations, while providing good documentation and aliases for Go idioms. For example, `OnDone` as an alias for `OnComplete`.

So, once there are multiple `Observable` implementations, my vote would be for the default to be compatible with other ReactiveX bindings, as I originally commented:

> The expected behavior would be for every `Observer` to receive the same items sent to the underlying channel. This is how it works in other ReactiveX implementations.

**Comment by avelino** [comment]
> One of the major selling points of ReactiveX is "cross-platform":
> 
> > Available for idiomatic Java, Scala, C#, C++, Clojure, JavaScript, Python, Groovy, JRuby, and others
> 
> I have personally used RxClojure, RxJava, RxJS and RxScala. It's true there are slight differences between implementations for practical reasons, but in general as a ReactiveX user I expect consistency across language bindings. It's one of the most awesome things about ReactiveX! Learn it once and you can leverage that knowledge for other languages as well.
> 
> I'm not vouching for disregarding Go specifics. I think it would be best to maintain consistency to other ReactiveX implementations, while providing good documentation and aliases for Go idioms. For example, `OnDone` as an alias for `OnComplete`.
> 
> So, once there are multiple `Observable` implementations, my vote would be for the default to be compatible with other ReactiveX bindings, as I originally commented:
> 
> > The expected behavior would be for every `Observer` to receive the same items sent to the underlying channel. This is how it works in other ReactiveX implementations.

I agree with @sorsasampo point of view of keeping the implementation closer to the official documentation, much point there's no way because it has the go language peculiarity

**Comment by jochasinga** [comment]
> > One of the major selling points of ReactiveX is "cross-platform":
> > > Available for idiomatic Java, Scala, C#, C++, Clojure, JavaScript, Python, Groovy, JRuby, and others
> > 
> > 
> > I have personally used RxClojure, RxJava, RxJS and RxScala. It's true there are slight differences between implementations for practical reasons, but in general as a ReactiveX user I expect consistency across language bindings. It's one of the most awesome things about ReactiveX! Learn it once and you can leverage that knowledge for other languages as well.
> > I'm not vouching for disregarding Go specifics. I think it would be best to maintain consistency to other ReactiveX implementations, while providing good documentation and aliases for Go idioms. For example, `OnDone` as an alias for `OnComplete`.
> > So, once there are multiple `Observable` implementations, my vote would be for the default to be compatible with other ReactiveX bindings, as I originally commented:
> > > The expected behavior would be for every `Observer` to receive the same items sent to the underlying channel. This is how it works in other ReactiveX implementations.
> 
> I agree with @sorsasampo point of view of keeping the implementation closer to the official documentation, much point there's no way because it has the go language peculiarity

That would require implementing `Observable` as a slice and each sequential element "emitted" will have to be copied to every `Observer`. Like I mentioned of this could be implemented as a default construct i.e. `ObservableList` or something that makes sense (meaning it does not go out of Go's way and/or sacrifice efficiency just to get along with ReactiveX) I'm down.

**Comment by teivah** [comment]
I believe we may have different alternatives than emitting elements by channels or slice copy.

### Proposition

First, let me explain roughly the changes I proposed:
* `Iterator` remains an interface but proposes two methods `Next() bool` and `Value() interface{}`. No real difference here but just a more idiomatic way to iterate on a structure, in my opinion.
* `Iterable` became an interface with only one `Iterator() Iterator` method.
* `Observable` became an interface with a list of operators but is also composed of `Iterable`.

To iterate over an `Observable`, every operator is doing it this way:

```go
it := observable.iterable.Iterator()
for it.Next() {
  item := it.Value()
  // Do something
}
```

If the upstream `Observable` emits items in a channel, `it.Next()` is just wrapping somehow the call to:

```go
item := <- observable.internalChannel
```

### Just operator

Let's now consider the `Just` operator which should produce a cold `Observable`, according to Rx standards.

In my proposition, `Just` creates another type of `Iterator`, not based on channels. It's simply a structure containing a pointer `s` to the initial slice and an `index`.
* When `it := observable.iterable.Iterator()` is called by an operator, it creates another structure with `index` set to 0.
* The `Iterator` implementation simply returns `s[index]` and increments `index` during each call to `Next()`.

This is an alternative than having to publish each elements to a channel or having to copy the slice to each observer.

### Other operators in the case of a cold Observable

Now, how to handle this very use case:

```go
Just(1).Map(f1).Map(f2).Subscribe(observer)
```

The first `Map` could iterate over the `Observable` produced by `Just` as I described above (no impacts).

Yet, how does the second `Map` iterates over the `Observable` produced by the first one?

* Solution 1: Keeping channels. The `Map` operator produces items in a dedicated channel.

* Solution 2: Chaining `Observer`.

When `Subscribe()` is called, it registers an `Observer` to the upstream `Observable` (the second `Map`). This also triggers the registration of the second `Map` as an `Observer` of the upstream `Observable` (the first `Map`). This also triggers the registration of the first `Map` as an `Observer` of the upstream `Observable` (`Just`). Everything done synchronously using the same goroutine.

Once the _registration_ process is done, the parent `Observable` emits the first element by calling `OnNext` with the first item. This triggers the first `Map` which operates the item and emits the result by calling `OnNext`. This triggers the second `Map` which operates the item and emits the result by calling `OnNext` etc etc.

Then, we repeat the process for all the elements produced by the parent `Observable` by again **chaining** the operations.

This is an alternative to manage cold `Observable` without being forced to use channels (in my humble opinion :)

**Comment by teivah** [comment]
Hey! I'm cleaning the backlog by removing the issues without updates for more than a year. Meanwhile, please check at the v2 to see if the issue is still relevant.
