### ISSUE TITLE
I wrote an implementation

### ISSUE THREAD

**Issue by langhuihui** [ReactiveX/RxGo#62]
[GoRx](https://github.com/langhuihui/GoRx)

**Comment by avelino** [comment]
We have a branch (rx-interfaces) where we are rewriting (refactoring) RxGo, I invite you to take a look at the path we are following and I count (very) with your and all community contribution

**Comment by jochasinga** [comment]
@langhuihui that looks great. We are making an overhaul of RxGo and could use your help / contributions.

**Comment by norandom** [comment]
@langhuihui is there a way to check out this work and to contribute to it as the moment?

**Comment by langhuihui** [comment]
what can I do for you?

**Comment by avelino** [comment]
Track the work that is being done in RxGo 2 (new version with interface support)
https://github.com/ReactiveX/RxGo/milestone/1

roadmap: https://github.com/ReactiveX/RxGo/issues/99#issuecomment-443816758

**Comment by guider** [comment]
so cool  and I'm waiting
