### ISSUE TITLE
go get -u github.com/jochasinga/rxgo is wrong, packages import from /rx, not /rxgo

### ISSUE THREAD

**Issue by lucaszanella** [ReactiveX/RxGo#7]
When I did `go get -u github.com/jochasinga/rxgo` as in the `readme` I got a folder called `rxgo`, but the imports in the `readme` are for a folder called `rx`. Tried to change the imports to `rxgo` but then the files inside the `rxgo` folder import also from `rx` folder, so I changed manually the name of `rxgo` folder to `rx`

**Comment by jochasinga** [comment]
@lucaszanella so did `go get githubcom/jochasinga/rx` works fine?

**Comment by lucaszanella** [comment]
@jochasinga this is a 404 page

**Comment by jochasinga** [comment]
@lucaszanella what did you mean 404 page? Usually, package name is independent from the main package directory. That means you can import RxGo with `go get -u github.com/jochasinga/rxgo` but can use `rx` as a package namespace as in `rx.iterable`.

**Comment by jochasinga** [comment]
Fixed by @ArekCzarnik. Agreed to use `rxgo` as the top-level namespace.
