### ISSUE TITLE
Operators Zip 

### ISSUE THREAD

**Issue by guider** [ReactiveX/RxGo#76]
> The `Zip` method returns an Observable that applies a function of your choosing to the combination of items emitted, in sequence, by two (or more) other Observables, with the results of this function becoming the items emitted by the returned Observable. It applies this function in strict sequence, so the first item emitted by the new Observable will be the result of the function applied to the first item emitted by Observable #1 and the first item emitted by Observable #2; the second item emitted by the new zip-Observable will be the result of the function applied to the second item emitted by Observable #1 and the second item emitted by Observable #2; and so forth. It will only emit as many items as the number of items emitted by the source Observable that emits the fewest items. 

reference http://reactivex.io/documentation/operators/zip.html

**Comment by teivah** [comment]
A PR tackling this feature: https://github.com/ReactiveX/RxGo/pull/86

**Comment by avelino** [comment]
implemented on RxGo 2 (in development) https://github.com/ReactiveX/RxGo/pull/95
