### ISSUE TITLE
No 'do' method?

### ISSUE THREAD

**Issue by lucaszanella** [ReactiveX/RxGo#8]
I've searched the documentation, I was trying to make the simplest rx stream just to test the library, it was supposed to be something like this:

`observable.just(1).do(fmt.Print).subscribe()`

Is there any documentation for the observable methods? I'm not that good in Go to be able to read the source

**Comment by jochasinga** [comment]
Hi @lucaszanella. `Do` is currently not implemented, but I'll look into it.

What you wanted to do can be achieved with

```go

// wrap a side effect in an EventHandler
handler := handlers.NextFunc(func(v interface{}) {
        fmt.Println(v)
})
sc := observable.Just(1).Subscribe(handler)
<-sc

// or ...

// wrap the side effect in a MappableFunc and throw away the returned Observable
_ = observable.Just(1).Map(func(v interface{}) interface{} {
        fmt.Print(v)
        return nil
})

```

Go has no generic functions, so it is not possible for a method to accept any function outside of the typed ones declared in `fx` and `handlers`.

**Comment by lucaszanella** [comment]
@jochasinga there's no possibility to pass a pointer to a generic function and execute it? By the way, thanks, I'm learning, Go is so different but I like it

**Comment by jochasinga** [comment]
@lucaszanella worth checking out [this discussion on stackoverflow](http://stackoverflow.com/questions/3601796/can-we-have-function-pointers-in-google-go).

It might be interesting to have `Do` as a shortcut operator for a subscription in `Connectable` though, since it is a cold Observable that doesn't fire the stream on `Subscribe`:

```go

printFunc := func(item interface{}) {
        fmt.Print(item)
}
c := connectable.Just(1).Subscribe(handlers.NextFunc(printFunc))
results := c.Connect()
<-results

// can be
results = connectable.Just(1).Do(printFunc).Connect()
<-results

```

**Comment by jochasinga** [comment]
Fixed -> [Implement Do Operator](https://github.com/ReactiveX/RxGo/commit/424756e4392d93505c7ba7d9d51c7131a6c2be10)
