### ISSUE TITLE
Implement the defer() function as described in Rx

### ISSUE THREAD

**Issue by makannan** [ReactiveX/RxGo#91]
We need a way to create an Observable that 'lazily' emits items only when subscribed to.

Implement the defer() function as described in Rx: http://reactivex.io/documentation/operators/defer.html

(Is there any way the current code base emit items *only* when subscribed to?)

**Comment by makannan** [comment]
More specifically, I see in observable/create.go line 36:
```
go func() {
		source(emitter, isClosed(emitted))
	}()
```

Shouldn't the above happen only when `Subscribe()` is called?

**Comment by makannan** [comment]
Here is a very simple test:
```
var _nextVal = 0

func nextInt() int {
	_nextVal = _nextVal + 1
	fmt.Printf("nextInt():: Emitting next int (%d)....\n", _nextVal)
	return _nextVal
}

func TestBasicCreateObservable(t *testing.T) {
	err := fmt.Errorf("some error")
	obsv := observable.Create(func(emitter *observer.Observer, disposed bool) {
		emitter.OnNext(nextInt())
		emitter.OnNext(nextInt())
		emitter.OnNext("some element which cannot be emitted")
		emitter.OnError(err)
		emitter.OnDone()
	})

	time.Sleep(time.Duration(10) * time.Second)

	fmt.Printf("Created observable: %v\n", obsv)
}
```

You would see: `nextInt():: Emitting next int (1)....`  eventhough `Subscribe()` wasn't called.

**Comment by teivah** [comment]
I've just created https://github.com/ReactiveX/RxGo/pull/92.

A concrete example:
```go
test := 5

var value int
onNext := handlers.NextFunc(func(item interface{}) {
	switch item := item.(type) {
	case int:
		value = item
	}
})

// First subscriber
stream1 := Defer(func() Observable {
	items := []interface{}{test}
	it, err := iterable.New(items)
	if err != nil {
		t.Fail()
	}
	return From(it)
})
test = 3
stream2 := stream1.Map(func(i interface{}) interface{} {
	return i
})
sub := stream2.Subscribe(onNext)
<-sub
assert.Exactly(t, 3, value)
```

Instead of getting 5, I'm getting 3 which is the value of `test` when we register a `Map` operator.

**Comment by makannan** [comment]
Hi Teiva,

How can I use defer to generate infinite stream of values?

**Comment by teivah** [comment]
Hey,

You could do something like this:
```go
stream1 := Defer(func() Observable {
	return Repeat(42)
})
```

**Comment by makannan** [comment]
Actually, I am fine with the signature of the `Defer()` method as long as there is a way to emit infinite (and dynamic) events. Waiting for you to merge !!

**Comment by teivah** [comment]
@makannan There is already an issue for this: https://github.com/ReactiveX/RxGo/issues/54
Maybe, you can bring a concrete use case if you have one in mind?

**Comment by teivah** [comment]
https://github.com/ReactiveX/RxGo/pull/95 included in v2
